name: vending_machine_kata
description: Dart version of the vending machine kata.

dependencies:
  w_flux: "2.9.4"
  over_react: "1.18.1"
  react: "3.6.0"

dev_dependencies:
  test: '0.12.26+1'
  over_react_test: '1.3.1'
  dart_dev: '1.8.1'
  dart_style: '1.0.8'

transformers:
- over_react
- test/pub_serve:
    $include: test/**.dart
- $dart2js