@TestOn('browser')
library test.unit.generated_runner_test;

// Generated by `pub run dart_dev gen-test-runner -d test/unit -e Environment.browser --genHtml`

import './vending_machine/views/stores/vending_machine_store_test.dart' as vending_machine_views_stores_vending_machine_store_test;
import './vending_machine/views/vending_machine_view_test.dart' as vending_machine_views_vending_machine_view_test;
import 'package:test/test.dart';
import "package:over_react/over_react.dart";

void main() {
  setClientConfiguration();
  enableTestMode();
  vending_machine_views_stores_vending_machine_store_test.main();
  vending_machine_views_vending_machine_view_test.main();
}